### ISSUE TITLE
能否关闭获取用户信息的通知

### ISSUE THREAD

**Issue by Felix2yu** [xmcp/pakku-advanced-filter#1]
打开视频页会弹出大量的「获取用户信息」的通知，能否不显示或者改为页面内显示？谢谢。
macOS 10.13.5
火狐 59.0.2
pakku 8.7
暴力猴 2.9.4

<img width="346" alt="wx20180429-205713 2x" src="https://user-images.githubusercontent.com/746990/39406881-76b40360-4bf0-11e8-8b9c-1aefad9ca6ac.png">
<img width="335" alt="wx20180429-210540 2x" src="https://user-images.githubusercontent.com/746990/39406929-18180396-4bf1-11e8-9481-2cf01af8c23d.png">

**Comment by xmcp** [comment]
通知应该会在完成后自动消失的才对，这个大概是bug。
打开任何一个视频都会一下冒出来这么多通知吗？感觉不应该呀……
