### ISSUE TITLE
这个扩展有没有能力屏蔽U+10000以后的Unicode字符

### ISSUE THREAD

**Issue by Nebelwerfer-G** [xmcp/pakku-advanced-filter#2]
RT，最近B站抽象人越来越多，部分视频里的(纯/含)emoji弹幕也多了起来。
曾经试过在[这个](https://github.com/xmcp/bilibili-ban-list)弹幕屏蔽列表里面以如下的方式加emoji位点，然后放到B站的Flv.js里面：

`<item enabled="true">r=^[^\u{1F600}-\u{1F64F}]</item>`
`<item enabled="true">r=^[^\u{1F300}-\u{1F560}]</item>`
`<item enabled="true">r=^[^\u{1F680}-\u{1F6FF}]</item>`
`<item enabled="true">r=^[^\u{1F900}-\u{1F9FF}]</item>`

但是连[regex101](https://regex101.com/r/AhKEX7/1)都告诉我在纯净JS环境下这么做不管用（会把后面的位点号识别成纯文本）
所以想问可不可以通过这个插件来实现对U+10000以后的Unicode字符的过滤

~~（不过问出这个问题之前有点隐隐感觉到这是个但凡是JS代码都难做到的事情………………）~~

**Comment by Nebelwerfer-G** [comment]
搞一个代理对就可以了
果然发 Issue 之前还是必须要学习一个
不然是图样图森破的
`<item enabled="true">r=^[^\uD83D[\uDE00-\uDE4F]]</item>`
`<item enabled="true">r=^[^\uD83C[\uDF00-\uE160]]</item>`
`<item enabled="true">r=^[^\uD83D[\uDE80-\uDEFF]]</item>`
`<item enabled="true">r=^[^\uD83E[\uDD00-\uDDFF]]</item>`

**Comment by xmcp** [comment]
http://link.acg.tv/forum.php?mod=viewthread&tid=11557
